Update README.md
VegaBobo/DSU-Sideloader pull request #110
Opened 2023-07-18 05:53 UTC by Poussinou

Hi,

This small PR adds a button to get your app on F-Droid 👍 It also removes the link to IzzyOnDroid, as your app is now in the official F-Droid repo.

It also adds a link to get the latest APK from the Releases Section.

You can now eventually add the [fdroid](https://github.com/topics/fdroid) and/or [f-droid](https://github.com/topics/f-droid) tags that will appear on the right side of the repo.

2023-07-23 01:03 UTC, merged

2023-07-23 01:03 UTC, VegaBobo commented
👍

2026-01-04 10:44 UTC, gibbsbradley66-sketch requested changes

2026-01-04 10:44 UTC, gibbsbradley66-sketch commented on README.md
> +     alt="Get it on F-Droid"
Alt=

2026-01-04 10:44 UTC, gibbsbradley66-sketch commented on README.md
> -| <a href="https://github.com/VegaBobo/DSU-Sideloader/releases"><img src="https://img.shields.io/github/v/release/VegaBobo/DSU-Sideloader?label=GitHub" /></a> |
<a

2026-01-04 10:44 UTC, gibbsbradley66-sketch commented on README.md
> +[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
<+

2026-01-04 10:44 UTC, gibbsbradley66-sketch commented on README.md
> -| <a href="https://apt.izzysoft.de/fdroid/index/apk/vegabobo.dsusideloader"><img src="https://img.shields.io/endpoint?url=https://apt.izzysoft.de/fdroid/api/v1/shield/vegabobo.dsusideloader" /></a> |
Img

2026-01-04 10:44 UTC, gibbsbradley66-sketch approved these changes

2026-01-04 10:45 UTC, gibbsbradley66-sketch commented on README.md
> -| <a href="https://apt.izzysoft.de/fdroid/index/apk/vegabobo.dsusideloader"><img src="https://img.shields.io/endpoint?url=https://apt.izzysoft.de/fdroid/api/v1/shield/vegabobo.dsusideloader" /></a> |
Src

2026-01-04 10:45 UTC, gibbsbradley66-sketch commented on README.md
> -| <a href="https://apt.izzysoft.de/fdroid/index/apk/vegabobo.dsusideloader"><img src="https://img.shields.io/endpoint?url=https://apt.izzysoft.de/fdroid/api/v1/shield/vegabobo.dsusideloader" /></a> |
Src

2026-01-04 10:45 UTC, gibbsbradley66-sketch commented on README.md
> -| <a href="https://apt.izzysoft.de/fdroid/index/apk/vegabobo.dsusideloader"><img src="https://img.shields.io/endpoint?url=https://apt.izzysoft.de/fdroid/api/v1/shield/vegabobo.dsusideloader" /></a> |
Src